
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - helloWorld
  - --runtime=nodejs14
  - --region=southamerica-east1
  - --source=.
  - --trigger-http
  - --trigger-resource=https://southamerica-east1-brave-ladybug.cloudfunctions.net/hello